config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  root to: 'home#index'
  get '/about', to: 'home#about'
  get '/help', to: 'home#help'

  post '/weights/create_from_rfid',
       to: 'weights#create_from_rfid',
       as: :weights_create_from_rfid
  ActiveAdmin.routes(self)
end

app/views/admin/stats/by_truck.html.erb
<h1><%= t("report_by_truck") %></h1>
<% if Truck.all.count <= 0 %>
  <div class="row alert alert-danger">
    <h2><%= I18n.t("no_trucks_defined") %></h2>
  </div>
  <% else %>
  <%= form_tag admin_stats_show_report_by_truck_path, method: :post do %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= label_tag t('truck_license') %>
      <%= select_tag :truck_id, options_from_collection_for_select(Truck.all, :id, :license),
          {class: "select2", id: "truck_id_select2", data: {url: all_options_admin_trucks_path(format: :json)} }%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= label_tag t("date_start") %>
      <%= text_field_tag :date_start, 
            nil,
            {
              data: {
                provide: 'datepicker',
                "date-format": "yyyy-mm-dd",
                "date-today-highlight": "true",
                "date-days-of-week-highlighted": "0",
                "date-autoclose": "true"
              },
              class: "form-control",
              autocomplete: "off"
            } %> <br>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
    <%= label_tag t("date_end") %>
    <%= text_field_tag :date_end,
            nil,
            {
              data: {
                provide: 'datepicker',
                "date-format": "yyyy-mm-dd",
                "date-today-highlight": "true",
                "date-days-of-week-highlighted": "0",
                "date-autoclose": "true"
              },
              class: "form-control",
              autocomplete: "off"
            } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <%= label_tag I18n.t("format") %>
      <%= select_tag :format, options_for_select([:HTML, :XLSX, :JSON])%>
    </div>
  </div>
  <div class="row">&nbsp;</div>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= button_tag t('get_report') %>
    </div>
  </div>
  <% end %>

<script type="text/javascript">
$(document).ready(function() {
  $("#truck_id").select2({
    placeholder: "Please select",
    ajax: {
      url: "/trucks/by_license.json",
      dataType: "json",
      results: function(data, page) {
        return { 
          results: $.map( data, function(person, i) {
            return { id: person.id, text: person.name }
          } )
        }
      }
    }
  });
});
</script>
<% end %>

app/views/admin/stats/daily_report.html.erb
<div class="row">
  <div class="col-md-7">
    <h2> <%= I18n.t("daily_report") %> </h2>
  </div>
  <div class="col-md-5">
    <h3> <%= day_date.to_formatted_s(I18n.t("date.format.short")) %></h3>
  </div>
</div>
<% report_rows.each do |rpt_row| %>
  <div class="row">
    <div class="col-md-4"><h4><%= I18n.t('driver') %>: <%= rpt_row[:driver] %></h4></div>
    <div class="col-md-4"><h4><%= I18n.t('truck') %>: <%= rpt_row[:truck].presence || I18n.t("absent") %></h4></div>
  </div>
  <hr />
  <% next if rpt_row[:truck].blank? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%=I18n.t('date_weight')%></th>
        <th><%=I18n.t('weight')%></th>
      </tr>
    </thead>
    <tbody>
    <% rpt_row[:weights].each do |item| %>
      <tr>
        <td><%= item[:weight_start].to_formatted_s(I18n.t("date.format.long")) %></td>
        <td><%= item[:measured_weight] %></td>
      <tr>
    <% end%>
    <tr>
      <th><%= I18n.t('net_total_weight')+":" %></th>
      <th><%= rpt_row[:total_weight].to_s %></th>
    </tr>
    </tbody>
  </table>
<% end %>
<div class="row">
  <div class="col-md-12 text-center">
    <h2><%= I18n.t("weight_by_driver") %></h2>
    <canvas id="dailyreport" width="800" height="400"></canvas>
  </div>
</div>
<div class="row">
  <div class="col-md-12 text-center">
    <h2><%= I18n.t("percentage_by_driver")%></h2>
    <canvas id="dailyreportpie" width="800" height="400"></canvas>
  </div>
</div>
<div class="text-center">
  <%= link_to I18n.t("another_report"), :back, class: "btn btn-primary", style: "color: white; text-decoration: none" %>
</div>
<script type="text/javascript">
  var ctx = document.getElementById("dailyreport");
  var dataLabels = <%=raw json_labels %>;
  var dataPoints = <%=raw json_data %>;
  var bgColors = getBackgroundColors(dataPoints);
  var myChart = new Chart(ctx, {
    type: "horizontalBar",
    data: {
      labels: dataLabels,
      datasets: [{
        label: "<%= I18n.t("total_weight_by_day") %>",
        data: dataPoints,
        backgroundColor: bgColors
      }]
    },
    options: {
      responsive: false
    }
  });

  var ctxPie = document.getElementById("dailyreportpie");
  var pieChart = new Chart( ctxPie, {
    type: "pie",
    data: {
      labels: dataLabels,
      datasets: [{
        label: "<%= I18n.t("total_weight") %>",
        data: dataPoints,
        backgroundColor: bgColors
      }]
    },
    options: {
      responsive: false
    }
  });
</script>

app/views/admin/stats/driver_performance_report.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= I18n.t("driver_performance_report") %></h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3><%= I18n.t("dates").humanize %>: <%= start_date %> <%= I18n.t("to") %> <%= end_date %></h3>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= I18n.t("driver")%></th>
          <th><%= I18n.t("total_weight")%></th>
        </tr>
      </thead>
      <tbody>
        <% report_rows[2].each do |weight_row| %>
        <tr>
          <td><%= weight_row[0] %></td>
          <td><%= weight_row[1] %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2><%= I18n.t("weight_by_driver") %></h2>
    <span>
      <canvas id="performance" width="800" height="400"></canvas>
    </span>
  </div>
</div>
<div class="row">
  <div class="col-md-12 text-center">
    <h2><%= I18n.t("percentage_by_driver")%></h2>
    <span>
      <canvas id="reportpie" width="800" height="400"></canvas>
    </span>
  </div>
</div>
<div class="text-center">
  <%= link_to I18n.t("another_report"), :back, class: "btn btn-primary", style: "color: white; text-decoration: none" %>
</div>
<script type="text/javascript">
var ctx = document.getElementById("performance");
  var dataLabels = <%=raw json_labels %>;
  var dataPoints = <%=raw json_data %>;
  var bgColors = getBackgroundColors(dataPoints);
  var myChart = new Chart(ctx, {
    type: "horizontalBar",
    data: {
      labels: dataLabels,
      datasets: [{
        label: "<%= I18n.t("total_weight") %>",
        data: dataPoints,
        backgroundColor: bgColors
      }]
    },
    options: {
      responsive: false
    }
  })

  var ctxPie = document.getElementById("reportpie");
  var pieChart = new Chart( ctxPie, {
    type: "pie",
    data: {
      labels: dataLabels,
      datasets: [{
        label: "<%= I18n.t("total_weight") %>",
        data: dataPoints,
        backgroundColor: bgColors
      }]
    },
    options: {
      responsive: false
    }
  });
</script>

app/views/admin/stats/report_by_driver.html.erb
<div class="row">
  <div class="col-md-6"><h1><%= I18n.t("report_by_driver")%></h1></div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2>
      <%= I18n.t("driver") %>: <%= driver.display_string %>
      <%= link_to admin_user_path(driver), title: I18n.t("view"), target: "_blank" do%><span class="fa fa-eye"></span><% end %>
    </h2>
  </div>
</div>
<div class="row">
  <div class="col-md-6 ">
    <h3>
      <%= I18n.t('truck') %>:<%= report_rows[:truck] %>
      <%= link_to admin_truck_path(report_rows[:truck]), title: I18n.t("view"), target: "_blank" do %><span class="fa fa-eye"></span><% end %>
    </h3>
  </div>
  <div class="col-md-6 text-right"><h3><%= I18n.t("dates").humanize %>: <%= date_start %> <%= I18n.t("to") %> <%= date_end %></h3></div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= I18n.t('date_weight') %></th>
      <th><%= I18n.t('weight') %></th>
    </tr>
  </thead>
  <tbody>
    <% report_rows[:weights].each do |item|%>
    <tr>
      <td><%= item[:weight_start] %></td>
      <td><%= item[:measured_weight] %></td>
    </tr>
    <% end %>
    <tr>
      <th><%= I18n.t('net_total_weight')+": "%> </th>
      <th><%= report_rows[:total_weight].to_s %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <canvas id="bydriver" width="800" height="400"></canvas>
  </div>
</div>
<script type="text/javascript">
  var ctx = document.getElementById("bydriver");
  var dataLabels = <%=raw json_labels %>;
  var dataPoints = <%=raw json_data %>;
  var bgColors = getBackgroundColors(dataPoints);
  var myChart = new Chart(ctx, {
    type: "horizontalBar",
    data: {
      labels: dataLabels,
      datasets: [{
        label: "<%= I18n.t("total_weight_by_day") %>",
        data: dataPoints,
        backgroundColor: bgColors
      }]
    },
    options: {
      responsive: false
    }
  })
</script>

app/views/admin/stats/report_by_truck.html.erb
<div class="row">
 <div class="col-md-6">
   <h1><%= I18n.t("report_by_truck") %></h1>
 </div>
</div>
<div class="row">
  <div class="col-md-6">
    <h2>
      <%= I18n.t('truck').humanize + ": " + truck.display_string %>
      <%= link_to  admin_truck_path(truck), title: I18n.t("view"), target: "_blank" do %><span class="fa fa-eye"></span><% end %>
    </h2>
  </div>
  <div class="col-md-6 text-right">
    <h3>Fechas: <%= date_start %> <%= I18n.t("to") %> <%= date_end %></h3>
  </div>
</div>
<% report_rows.each do |item| %>
  <table class="table table-stripped">
    <thead>
      <tr>
        <th><%= I18n.t("driver") %></th>
        <th><%= I18n.t("weights") %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <h3><%= item[:driver]%></h3>
          <%= link_to admin_user_path(item[:driver]), title: I18n.t("view"), target: "_blank " do %><span class="fa fa-eye"></span><% end %>
        </td>
        <td>
          <table class="table table-stripped">
            <tr>
              <th><%=I18n.t('date_weight')%></th>
              <th><%= I18n.t('weight') %></th>
            </tr>
            <% item[:weights].each do |weight_row| %>
            <tr>
              <td><%= weight_row[:weight_start].to_formatted_s(I18n.t("date.format.long")) %></td>
              <td><%= weight_row[:measured_weight] %></td>
            </tr>
            <% end %>
            <tr>
              <th><%=I18n.t('net_total_weight') %>:</th>
              <th><%= item[:total_weight].to_s %></th>
            </tr>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
  <h3>
    
  </h3>
  <div class="row">
    <div class="col-md-12 text-center">
      <canvas id="bytruck" width="640" height="480"></canvas>
    </div>
  </div>
  <script type="text/javascript">
  var ctx = document.getElementById("bytruck");
  var dataLabels = <%=raw json_labels %>;
  var dataPoints = <%=raw json_data %>;
  var bgColors = getBackgroundColors(dataPoints);
  var myChart = new Chart(ctx, {
    type: "horizontalBar",
    data: {
      labels: dataLabels,
      datasets: [{
        label: "<%= I18n.t("total_weight_by_day") %>",
        data: dataPoints,
        backgroundColor: bgColor
      }]
    },
    options: {
      responsive: false
    }
  })
  </script>
<% end %>